### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by hrace009** [veritrans/vt-web-whmcs#1]
Halo,
Barusan tadi coba integrasikan WHMCS saya, dan mendapat error seperti dibawah ini:

```
[28-Aug-2016 23:07:09 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Veritrans Error (500): Sorry our system has experienced an internal error, we will fix it as soon as possible' in /home/whmcs/public_html/whmcs/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php:96
Stack trace:
#0 /home/whmcs/public_html/whmcs/modules/gateways/veritrans-lib/Veritrans/ApiRequestor.php(17): Veritrans_ApiRequestor::remoteCall('https://api.san...', 'VT-server-LAyID...', false, false)
#1 /home/whmcs/public_html/whmcs/modules/gateways/veritrans-lib/Veritrans/Transaction.php(17): Veritrans_ApiRequestor::get('https://api.san...', 'VT-server-LAyID...', false)
#2 /home/whmcs/public_html/whmcs/modules/gateways/veritrans-lib/Veritrans/Notification.php(20): Veritrans_Transaction::status('6367d745-d302-4...')
#3 /home/whmcs/public_html/whmcs/modules/gateways/callback/veritrans.php(45): Veritrans_Notification->__construct()
#4 {main}

Next exception 'Exception' with message 'Veritrans Error (500): Sorry our system has experienced an internal in /home/whmcs/public_html/whmcs/includes/classes/WHMCS/Terminus.php on line 0
```

Bagaimana kah solusi nya?

Terima Kasih

**Comment by rizdaprasetya** [comment]
Halo @hrace009 , error 500 ini terjadi di sisi API, biasanya karena syntax pada request API ada yang salah. Untuk saya bantu melakukan pengecekan cause dari error ini, mohon infokan anda mendaftar akun veritrans dengan **email**/no **Merchant ID**/**Nama Merchant** apa. Akan kami bantu cek di log API kami.

Thanks.

**Comment by hrace009** [comment]
Halo mas Rizda,

Merchant ID: M096209

Email: hrace009@gmail.com

**Comment by rizdaprasetya** [comment]
@hrace009 
Maaf untuk transaksi tersebut lognya tidak ditemukan, silahkan coba lakukan testing lagi, jika ada error sekarang akan kami cek di log, agar bisa dibantu.

**Comment by hrace009** [comment]
halo mas @rizdaprasetya , seperti nya testing dari sandbox sudah sukses

**Comment by hrace009** [comment]
mas @rizdaprasetya , maaf saya ralat, seperti nya masih belum, tadi bisa sukses karena ada kesalahan di webserver saya, sekarang sudah saya fix, tapi masih 
Failed
Please check your request body

**Comment by yocki-s** [comment]
hi @hrace009 

Boleh tau saat test transaksi di sandbox/production?
ada order_id atau email customer, sehingga kita bisa cek di log.

btw, apakah dari sisi mas ada log parameter yg dikirim ke Veritrans? jika ada, boleh diberikan ke kami juga.

**Comment by rizdaprasetya** [comment]
@hrace009 atau mungkin bisa diberikan link untuk kami test coba pembayaran di whmcsnya? karena log tidak ditemukan setelah dicari berdasarkan MID anda.

**Comment by hrace009** [comment]
body {
width: 100% !important;
}
.ReadMsgBody {
width: 100%;
}
.ExternalClass {
width: 100%;
}
body {
-webkit-text-size-adjust: none;
}
body {
margin: 0; padding: 0;
}
img {
border: 0 none; height: auto; line-height: 100%; outline: none; text-decoration: none;
}
body {
background-color: #f8f8f8;
}



















































Halo reply@reply.github.com, Harris  yogasara Memberikanmu Credits Sebesar Rp10.000!










Harris  yogasara

mengundangmu untuk bergabung ke Bukalapak. Dapatkan Credits Rp10.000 milikmu dengan bergabung dan berbelanja di Bukalapak sekarang. Caranya mudah:



Bergabung & Dapatkan Credits





Klik tombol "Bergabung & Dapatkan Credits" di atas dan daftarkan akunmu


Atau kamu bisa mendaftar dengan membuka website
Bukalapak,
kemudian klik tombol "Daftar" di bagian kanan atas halaman beranda Bukalapak


Pada saat mendaftar tersebut, masukkan kode

hrace009137v

pada kolom "Kode Referral"


Setelah itu kamu tinggal lakukan transaksi minimum Rp100.000 paling lambat 14 hari setelah mendaftar


Selamat! Kamu mendapatkan Credits Rp10.000




Yuk, daftar dan berbelanja sekarang!



bukalapak.com/rf/hrace009137v































Segala bentuk informasi seperti

nomor kontak, alamat e-mail, atau password kamu bersifat rahasia.

Jangan menginformasikan data-data tersebut kepada siapa pun, termasuk kepada pihak yang mengatasnamakan Bukalapak.



























Copyright © 2018 PT Bukalapak.com. All Rights Reserved


Plaza City View Lt. 1 Jl. Kemang Timur No. 22


Jakarta Selatan Indonesia 12510















































































Anda memperoleh e-mail ini karena keanggotaan Anda pada Bukalapak.com. Anda bisa mengubah
pengaturan notifikasi
kapan pun.









Harap jangan membalas e-mail ini, karena e-mail ini dikirimkan secara otomatis oleh sistem.
