### ISSUE TITLE
WHMCS 7.0.2

### ISSUE THREAD

**Issue by dionstr** [veritrans/vt-web-whmcs#2]
halo ^^
Apakah modul ini support di WHMCS 7.0.2?
Untuk WHMCS ada 2 jenis modul ya? manakah yang berjalan dengan baik, SNAP atau VT-Web?

Thanks. :)

**Comment by rizdaprasetya** [comment]
Sebaiknya gunakan yang versi SNAP. Namun tidak pernah di tes untuk WHMCS v 7.x
Silahkan dicoba dahulu, jika tidak bisa berarti versi tersebut belum di support.
