### ISSUE TITLE
500 Error - Laravel

### ISSUE THREAD

**Issue by icangku** [veritrans/vt-web-whmcs#3]
[2017-07-26 13:28:22] local.ERROR: App\Exceptions\VeritransException: Veritrans Error (500): Sorry our system has experienced an internal error, we will fix it as soon as possible in /home/mxvistore/public_html/pos/core/app/Veritrans/Veritrans.php:129
Stack trace:
#0 /home/mxvistore/public_html/pos/core/app/Veritrans/Veritrans.php(65): App\Veritrans\Veritrans::remoteCall('https://api.san...', 'VT-server-Em8Yq...', Array, true)
#1 /home/mxvistore/public_html/pos/core/app/Veritrans/Veritrans.php(143): App\Veritrans\Veritrans::post('https://api.san...', 'VT-server-Em8Yq...', Array)
#2 /home/mxvistore/public_html/pos/core/app/Http/Controllers/VtwebController.php(180): App\Veritrans\Veritrans->vtweb_charge(Array)

**Comment by icangku** [comment]
Sorry Salah masukin seharusnya ke Laravel, tapi boleh bantu kah?

**Comment by harrypujianto** [comment]
tadi sistem midtrans sdg ada masalah. silahkan dicoba kembali
